### ISSUE TITLE
Dealing with non-stationary data

### ISSUE THREAD

**Issue by klowrey** [JuliaML/LearningStrategies.jl#19]
I'm grateful to have stumbled across this package's release on the julia discourse page just as I was starting to think about writing my reinforcement learning code base. The framework is nearly perfect for what I need and significantly more concise and clear than what I was doing before (which was very un-julia like).

I was wondering if you had applied some thought to how to deal with generated data. In many reinforcement learning problems, the `data` the optimization uses changes from iteration to iteration (for example when we use the current best performing model to collect new rewards from the environment). One method I thought of to use with LearningStrategies would be to have a MetaStrategy that, in the `update! ` function, collects new data and stores it in scratch space in `model`. The next MetaStrategy could then look at the data and calculate and apply a gradient to the model parameters.

The issue I see with this is forcing model to be a data store for elements needed between strategies. This could be fine for the most part as it seems to use `model` for this functionality already (ie. if I want to `Tracer` the norm of the gradient, the gradient has to be cached in the model). Some algorithms/MetaStrategies may not need all caches I'd have to give `model`. My question **is if there is a better way to accomplish data generation.** I'm still not 100% Julia congruent, but packages like this one really help me see the light. Thank you.

**Comment by joshday** [comment]
I don't completely follow what you need, but if your data is changing, you could make a learning strategy that modifies the `data` inside the `hook` function.

**Comment by klowrey** [comment]
In most reinforcement learning settings, the data you learn from is
collected from interactions with some environment, instead of given as
(x,y) pairs. Instead of iterating through a list of data, we would
generally have a pre-hook function that does this collection before passing
the data somehow to our update function, and running until convergence or
for some number of iterations.

The way I thought of doing this using this package is to use the Struct
that iterates over nothing, and, in a sense, overloading the update
function with a Strategy that does the data collection; the collected data
would be stored in model.

I just wanted a sanity check from folks in case there was a better way of
doing this. Long story short: in RL you have repeated interactions with an
environment, not iterate over a data set.

**Comment by klowrey** [comment]
I just saw that Reinforce.jl uses this package, so I can take a look over there for inspiration. Thanks.
