### ISSUE TITLE
"Documentation" notebook

### ISSUE THREAD

**Issue by dominusmi** [JuliaML/LearningStrategies.jl#21]
Hello everyone,

As part of a university group project (University of Warwick), we have been reviewing a lot of packages from the machine learning community of Julia, and have made some reports.

One of the task that I did was reviewing this package, and creating a notebook helping the user understand the package, implement custom models and strategies, and use built-in ones. 
Here is the current link to the notebook.

https://github.com/dominusmi/warwick-rsg/blob/master/Scouting/LearningStrategies.ipynb

I think it might be a useful add-on to the repository, to help newcomers understand how to use it and such. If you agree, let me know and I'll fork + pull request.

Obviously, any modifications is welcome!
Thank you and have a good day!

**Comment by tbreloff** [comment]
Holy 💩 this is awesome. This should be prominently linked at the top of
the readme.

You should get an A+, and your professor should be commended for the great
project.

**Comment by dominusmi** [comment]
Wow, great to hear! I'll tell my professor, you never know.. :wink: 
I'll initiate a pull request in about a week then, once the final structure of our repository has been fixed :smile: 
Thanks for everything!
