### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by CiaranOMara** [JuliaML/LearningStrategies.jl#25]
Is there a reason that the `hook` methods do not resolve to `hook(s::LearningStrategy, model) = nothing`?

I'm finding that I do not always want to include the iteration parameter in the `hook` and am wondering why the following is not implemented?
```julia
hook(s::LearningStrategy, model) = nothing
hook(s::LearningStrategy, model, i) = hook(s, model)
hook(s::LearningStrategy, model, data, i) = hook(s, model, i)
```

**Comment by joshday** [comment]
Just an oversight, I think.  Would you be willing to make a PR?
